stages:
  - mirror

mirror_to_eiman_github_project:
  stage: mirror
  variables:
    URL: "https://${EIMAN_NAME}:${PERSONAL_ACCESS_TOKEN}${GITHUB_URL}"
  only:
    - develop
    - main
  script:
    - git config user.email "${EIMAN_EMAIL}"
    - git config user.name "${EIMAN_NAME}"
    - git remote add github_repo "${GITHUB_URL}"
    - git checkout $CI_COMMIT_REF_NAME
    - git push --force github_repo $CI_COMMIT_REF_NAME
  after_script:
    - git remote remove github_repo
