stages:
  - mirror
  - test

copy_all:
  stage: mirror
  variables:
    URL: "https://${ES_NAME}:${ES_TOKEN}${REPO_ALL}"
  script:
    - git config user.email "${ES_EMAIL}"
    - git config user.name "${ES_NAME}"
    - git remote add copy_all "${URL}"
    - git checkout $CI_COMMIT_REF_NAME
    - git push --force copy_all $CI_COMMIT_REF_NAME
  after_script:
    - git remote remove copy_all



copy_server:
  stage: mirror
  variables:
    URL: "https://${ES_NAME}:${ES_TOKEN}${SERVER_REPO}"
  script:
    - git config user.email "${ES_EMAIL}"
    - git config user.name "${ES_NAME}"
    - cd server
    - git remote add copy_server "${URL}"
    - git checkout $CI_COMMIT_REF_NAME
    - git push --force copy_server $CI_COMMIT_REF_NAME
  after_script:
    - git remote remove copy_server

test_server:
  stage: test
  script:
    - cd server
    - npm install
    - npm test
