variables:
  ES_EMAIL: "eimansalleh.5@gmail.com"
  ES_NAME: "eimanes"

stages:
  - mirror
  - test

variables:
  GIT_TERMINAL_PROMPT: "1"

copy_server:
  stage: mirror
  variables:
    URL: "https://${ES_NAME}@github.com/${ES_NAME}/server-only.git"
    GitLab_REPO_URL: https://gitlab.com/freelance-adil-eiman/portfolio-project.git
  script:
    - git config user.email "${ES_EMAIL}"
    - git config user.name "${ES_NAME}"
    - git clone --mirror "${GitLab_REPO_URL}" || { echo "Failed to clone GitLab repository"; exit 1; }
    - cd portfolio-project.git || { echo "Failed to enter the GitLab repository directory"; exit 1; }
    - git remote add github "${URL}" || { echo "Failed to add GitHub remote"; exit 1; }
    - git fetch || { echo "Failed to fetch from GitLab"; exit 1; }
    - git sparse-checkout init --cone || { echo "Failed to initialize sparse-checkout"; exit 1; }
    - git sparse-checkout set 'server' || { echo "Failed to set sparse-checkout"; exit 1; }
    - git push github --mirror || { echo "Failed to push to GitHub"; exit 1; }
  after_script:
    - git remote rm github || { echo "Failed to remove GitHub remote"; exit 1; }

test_server:
  stage: test
  script:
    - cd server
    - npm install
    - npm test
